### ISSUE TITLE
ApdexMiddleware measures only web sockets requests

### ISSUE THREAD

**Issue by vjacquet** [AppMetrics/AppMetrics#605] opened 2020-09-01 19:38 UTC
Regular HTTP requests are not measured when `context.WebSockets.IsWebSocketRequest` is **false**, therefore the apdex score is 1 for a sample size of 0 for Application.HttpRequests's context.

https://github.com/AppMetrics/AppMetrics/blob/7474c6552f8474b705036a76e81c44c1be6ec791/src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/ApdexMiddleware.cs#L40-L45

Before #557, all requests were measured. Is this new behavior by design?

**Comment by alhardy** [comment] 2020-09-02 08:21
Nope that's not by design,  looks like that bug stuck in via a PR. The condition should be inverted.

**Comment by alhardy** [comment] 2020-10-08 10:22
Already fixed in latest preview

**Closed by alhardy** 2020-10-08 10:22 UTC
Labels: bug
