### ISSUE TITLE
Unable to report health metrics to graphite 

### ISSUE THREAD

**Issue by chiragsh** [AppMetrics/AppMetrics#280] opened 2018-05-29 12:57 UTC
Can somebody help me to configure reporting the health metrics to graphite ? I am able to report all the MVC metrics but the app is not reporting the health metrics. The health check endpoints are working also.

**Comment by alhardy** [comment] 2018-05-29 13:55
Duplicate of https://github.com/AppMetrics/Health/issues/9

**Closed by alhardy** 2018-05-29 13:55 UTC
