### ISSUE TITLE
.NET Core 2.2 Compatibility?

### ISSUE THREAD

**Issue by mts57017** [AppMetrics/AppMetrics#352] opened 2019-01-22 18:17 UTC
Hi, 

Quick question, is App Metrics compatible with .NET Core 2.2, or been tested?

**Comment by bberberoglu** [comment] 2019-01-23 05:55
Hi,
I used AppMetrics with .NetCore 2.2, and i have never encountered an error.

**Comment by bberberoglu** [comment] 2019-01-23 05:58
Please check : Duplicate of #340

**Closed** 2019-01-31 11:34 UTC
Labels: duplicate
